//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PckStudio.ModelSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PckStudio.ModelSupport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///  &quot;bat&quot;: {
        ///    &quot;textureSize&quot;: { &quot;X&quot;: 64, &quot;Y&quot;: 64 },
        ///    &quot;parts&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;head&quot;,
        ///        &quot;boxes&quot;: [
        ///          { &quot;pos&quot;: { &quot;X&quot;: -3, &quot;Y&quot;: -3, &quot;Z&quot;: -3 }, &quot;size&quot;: { &quot;X&quot;: 6, &quot;Y&quot;: 6, &quot;Z&quot;: 6 }, &quot;uv&quot;: { &quot;X&quot;: 0, &quot;Y&quot;: 0 } }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;body&quot;,
        ///        &quot;boxes&quot;: [
        ///          { &quot;pos&quot;: { &quot;X&quot;: -3, &quot;Y&quot;: 4, &quot;Z&quot;: -3 }, &quot;size&quot;: { &quot;X&quot;: 6, &quot;Y&quot;: 12, &quot;Z&quot;: 6 }, &quot;uv&quot;: { &quot;X&quot;: 0, &quot;Y&quot;: 16 } },
        ///          { &quot;pos&quot;: { &quot;X&quot;: -5, &quot;Y&quot;: 16, &quot;Z&quot;: 0 }, &quot;size&quot;: { &quot;X&quot;: 10, &quot;Y&quot;: 6, &quot;Z&quot;: [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string defaultModels {
            get {
                return ResourceManager.GetString("defaultModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///  &quot;bat&quot;: {
        ///    &quot;textureLocations&quot;: [
        ///      &quot;res/mob/bat&quot;
        ///    ],
        ///    &quot;materialName&quot;: &quot;bat&quot;,
        ///    &quot;parts&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;head&quot;,
        ///        &quot;children&quot;: [
        ///          { &quot;name&quot;: &quot;rightEar&quot; },
        ///          { &quot;name&quot;: &quot;leftEar&quot; }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;body&quot;,
        ///        &quot;children&quot;: [
        ///          {
        ///            &quot;name&quot;: &quot;rightWing&quot;,
        ///            &quot;children&quot;: [
        ///              { &quot;name&quot;: &quot;rightWingTip&quot; }
        ///            ]
        ///          },
        ///          {
        ///            &quot;name&quot;: &quot;leftWing&quot;,
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string modelMetaData {
            get {
                return ResourceManager.GetString("modelMetaData", resourceCulture);
            }
        }
    }
}
